name: Deploy Flask Backend to Azure Web App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive app for deployment
        run: zip -r app.zip . -x '*.git*'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: flask-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: flask-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_AZURE_APP_NAME>
          publish-profile: ${{ secrets.AZURE_WEB_
