name: Deploy Flask Backend to Azure

env:
  AZURE_WEBAPP_NAME: sarada  # Your Azure Web App name
  PYTHON_VERSION: '3.10'     # Using stable Python version

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          # No caching to avoid 422 errors
      
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn
      
      - name: Prepare deployment package
        run: |
          mkdir -p deploy_package
          cp -r backend/* deploy_package/
          
          # Create web.config
          cat > deploy_package/web.config << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <handlers>
                <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
              </handlers>
              <httpPlatform processPath="%home%\python\3.10\python.exe"
                            arguments="%home%\site\wwwroot\run.py"
                            stdoutLogEnabled="true"
                            stdoutLogFile="%home%\LogFiles\python.log"
                            startupTimeLimit="60">
                <environmentVariables>
                  <environmentVariable name="PYTHONPATH" value="%home%\site\wwwroot"/>
                </environmentVariables>
              </httpPlatform>
            </system.webServer>
          </configuration>
          EOF
          
          # Create run.py
          cat > deploy_package/run.py << 'EOF'
          from subprocess import Popen
          import os
          
          # Start gunicorn
          cmd = 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'
          Popen(cmd, shell=True)
          EOF
      
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './deploy_package'
