name: Deploy Flask Backend to Azure

env:
  AZURE_WEBAPP_NAME: sarada  # Your Azure Web App name
  PYTHON_VERSION: '3.10'     # Using stable Python version

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          # No caching to avoid 422 errors
      
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn
      
      - name: Prepare deployment package
        run: |
          mkdir -p deploy_package
          cp -r backend/* deploy_package/
          echo "gunicorn --bind=0.0.0.0 --workers=2 app:app" > deploy_package/startup.txt
      
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './deploy_package'
